create table USERS
(
    ID       BIGINT generated by default as identity (start with 4),
    USERNAME CHARACTER VARYING(255) not null
        constraint USERS_USERNAME
            unique,
    constraint USERS_PK
        primary key (ID)
);